=== sohyoun/Kitri---HTML5/xmltest/WebContent/book.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT booklist (book+)>
		<!ELEMENT book (title, author, publisher, price, discription?)>
				<!ELEMENT title (#PCDATA)>
				<!ELEMENT author ((name|writer), tel, address)>
					<!ELEMENT name (#PCDATA)>
					<!ELEMENT writer (#PCDATA)>
					<!ELEMENT tel (#PCDATA)>
					<!ELEMENT address (#PCDATA)>
				<!ELEMENT publisher (#PCDATA)>
				<!ELEMENT price (#PCDATA)>
				<!ELEMENT discription (#PCDATA)>
			
	<!ATTLIST book 
				id ID #REQUIRED
				kind (IT|소설|수필) "IT"
	>
	<!ATTLIST name sex (남|여) "남">
	<!ATTLIST writer sex (남|여) "남">

=== sohyoun/Kitri---HTML5/xmltest/WebContent/book.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE booklist SYSTEM "book.dtd">

<booklist>
<book id="isbn">
	<title>나미야잡화점의 비밀</title>
	<author>
		<name>고세라</name>
		<tel>01057773333</tel>
		<address>경기도 안양시</address>
	</author>
	<publisher>소현이네</publisher>
	<price>12000</price>
</book>

<book id="isb" kind="소설">
	<title>메롱롱</title>
	<author>
		<writer sex="여">박미래</writer>
		<tel>01057778888</tel>
		<address>경기도 안양시</address>
	</author>
	<publisher>소현이네</publisher>
	<price>12000</price>
</book>

</booklist>
